[build]
  command = "npx ng build --configuration production --base-href /"
  publish = "www"

# Force SPA routing (all paths return index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) lock Node to what you use locally
[build.environment]
  NODE_VERSION = "20"